source/api/pubsub.md

As seen in meteor/meteor#3764 and many other threads around the web, the merging of separately published versions of the same document is currently insufficiently documented.

Document the limitations of merging seperately published docs

---

Contributing.md
scripts/api-box.js
source/api/collections.md
source/api/methods.md
source/api/packagejs.md
source/packages/coffeescript.md
source/packages/modules.md

Okay, one last time! Moving here from https://github.com/meteor/meteor/pull/6636.
This PR expands the Modules » Syntax section to include subsections for CommonJS and CoffeeScript syntax. There’s a bit of repetition between the two, since CoffeeScript is just compiling into CommonJS, but I think we should keep the duplication since I doubt most people would read the syntax section that doesn’t apply to them. I also cribbed a little from the [CommonJS section of the Guide](http://guide.meteor.com/structure.html#using-require); I’m not sure what should go here versus there. If anything I think the CommonJS discussion is probably better off here, if the point of the Guide is to explain recommended practices (which obviously CommonJS is not). The caveat that the Guide points out, about how …

Documentation of how to use modules with CommonJS syntax or in CoffeeScript

---

source/packages/accounts-ui.md

TIL that I need to `{% raw %}` and `{% endraw %}` any Blaze template includes because of the `>`.  Fixes breaking change in #21 that prevents hexo server from starting (even though I thought I tried it with `hexo server` previously).

Added "raw" wrapper around tags from #21

---

source/api/assets.md

meteor/meteor#6784 brought this up.  Since it's different than almost every other Meteor package, it should probably be explained that it's one of the two exceptions (Npm is the other)

Explain that `Assets` does not need to be imported

---

source/api/passwords.md

This is a tiny grammar fix for the `Accounts.sendVerificationEmail` section of API docs.
It says _Send an email with a link the user can use verify their email address._
IMO it should say _Send an email with a link the user can use to verify their email address._

Fix some grammar

---

source/api/passwords.md

Provides clarification between Accounts.emailTemplates.from, which takes a string, and Accounts.emailTemplates.resetPassword.from, which takes a function.

Add resetPassword example

---

source/api/accounts-multi.md

Per my comments in meteor/docs#64, `onLogout` is available on both client and server and should be in the `AccountsCommon` section of the docs.
Closes meteor/docs#64

Move Accounts `onLogout` into the `AccountsCommon` section

---

source/packages/modules.md

See https://github.com/meteor/meteor/pull/6691

Support for ES2015 in backticks was added in Meteor 1.3.3

---

source/commandline.md

The `meteor npm` command is useful for ensuring your using the right version when deploying, and it's missing from the docs. This PR adds it and include `meteor node` for completeness.

Add `meteor npm` and `meteor node`

---

source/api/blaze.md

The old link was broken. This one works.

Fixed Link to Blaze API Docs

---

source/api/templates.md

The old link was broken. I fixed it here.

Fixed Link to Blaze Template API Docs

---

source/api/blaze.md

Now just pointing to the domain, that is less likely to change.

Link to Blaze documentation was broken after #86

---

source/commandline.md

It should be made clear that in lieu of a tarball, the `--directory` argument can be passed to `meteor build` to produce a `bundle` directory.
Related to meteor/meteor#7587

Indicate that `meteor build` can produce a directory as well.

---

source/api/http.md

As on posted on `https://forums.meteor.com/t/solved-meteor-http-client-sided-post-produces-options-call/30221/6` I improve the docs with warning about the client sided option-call if you use the same code as on the server and have a really basic rest-api where you need to implement the options-call yourself.
e.g. simplehttpserver in python has a really strange way of telling you that there is a problem as it tells you that the OPTIONS-Method is not defined. Because POST, GET, etc is also called method this mislead me into thinking that meteor does strange things here.

Include Paragraph about OPTIONS-Call on client

---

source/api/tracker.md

One link to the Tracker manual had an unclosed anchor tag and another one referenced the old manual.meteor.com domain.

Fix links to Tracker manual

---

source/api/collections.md

The docs linked to 1.4 but Meteor uses 2.2.

Update link to MongoDB driver

---

source/api/collections.md

The sort specifiers example was missing the language identifier.

Fix JavaScript syntax highlighting

---

source/api/accounts.md

This adds details about what options other `accounts-*` packages support:
* Google supports [many](https://developers.google.com/identity/protocols/OpenIDConnect#authenticationuriparameters)
* Facebook supports [`auth_type`](https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow#reaskperms)
* Twitter supports [`force_login`](https://dev.twitter.com/oauth/reference/get/oauth/authenticate)
These are all supported in the Meteor code too, just not documented.
Related to meteor/meteor#7584 meteor/meteor#7078 and meteor/meteor#7820

Add details about other options that the `accounts-*` packages support

---

source/api/email.md

It's not in https://tools.ietf.org/html/draft-earhart-url-smtp-00
it's not necessary in practice.
It's not in most of the web tutorials out there.

Remove trailing /

---

source/packages/modules.md

CoffeeScript since 1.11 (and the Meteor `coffeescript` package since 1.11.x) support ES2015-style `import` and `export` statements. The docs can leave out the explanations of CommonJS workarounds for CoffeeScript now.
https://forums.meteor.com/t/coffeescript-1-11-0-now-supports-es6-modules/29750

CoffeeScript supports import/export syntax now.

---

source/commandline.md

The "login locations" page was removed (unintentionally?) from www.meteor.com last year. We should probably reinstate it, but until then let's remove the dangling link.

Remove reference to token revocation

---

source/commandline.md

This adds further details about the importance of the `meteor node` and
`meteor npm` commands.
I've added this to provide an easy place to link to from the Meteor
Tutorials (and other locations!) and was inspired to do so trying to follow up on
meteor/tutorials#68 where I couldn't help but understand the developer's confusion since it hadn't been explained earlier in the tutorial.
This PR is a requirement for meteor/tutorials#116.
Critique is appreciated (if necessary) but feel free to merge if it looks good!

Update `meteor node` and `meteor npm` command line documentation.

---

source/packages/oauth-encryption.md

The old command doesn't work anymore because there is no *~/.meteor/tools* directory.

Use `meteor node` in OAuth key generation command

---

source/api/passwords.md

Surprisingly these weren't documented and had to retrieve the template names from the actual source code. Added them for convenience with additional example of how they could be set.

Added emailTemplates documentation

---

source/api/accounts-multi.md
source/api/accounts.md
source/api/assets.md
source/api/check.md
source/api/collections.md
source/api/connections.md
source/api/core.md
source/api/ejson.md
source/api/email.md
source/api/http.md
source/api/methods.md
source/api/mobile-config.md
source/api/packagejs.md
source/api/passwords.md
source/api/pubsub.md
source/api/reactive-var.md
source/api/session.md
source/api/tracker.md
source/packages/appcache.md
source/packages/ecmascript.md
source/packages/modules.md
source/packages/oauth-encryption.md
source/packages/webapp.md

This pull request updates all code examples to use newer ECMAScript features and a more modern (and consistent) code style. If you think that I changed too much or if you prefer a different code style or formatting, I'd be happy to change it again, of course. :smile:
These are some of the changes I made:
* No more globals
* Arrow functions where `this` would be `window`/`global`. Publication functions, for example, still use `function`s, even if `this` isn't used.
* Shorter syntax for function definitions on object initializers
* More and consistent spacing to improve readability, for example using a space after opening and before closing braces for single line object literals.
* Single quotes instead of double quotes. The Guide and more recent code in the Docs also use single quotes.
* …

Modernize examples (ECMAScript and code style)

---

source/api/accounts-multi.md

To fully modernize this example and make it functional, I modified the function to use `Object.assign` to create a new user object to return instead of changing the passed in argument.
This could go one step further and change `options` to a destructured `{profile}` but there may be arguments against that. Let me know if you want me to destructure options.

Use Object.assign instead of changing the argument

---

source/api/tracker.md

`Tracker.inFlush()` was added with meteor/meteor#8565

add Tracker.inFlush() to documentation

---

source/api/http.md

Invalid syntax fixed in documentation of HTTP.call

Fix syntax of function in HTTP.call example

---

source/api/collections.md

One very small change, since I just came across it.
Removed the potentially insecure example of:
```
Messages.find({ userId: Session.get('myUserId') })
```
with the more secure (and non-Session):
```
Messages.find({ userId: Meteor.userId() })
```
We really don't want to accidentally encourage people to store the current `userId` in the `Session` global

Replace insecure `Session.get('myUserId')` in api/collections.md

---

source/api/packagejs.md

This is supposed to link to:
```html
<a href="#PackageNamespace-registerBuildPlugin" class="link primary">
<em>Package</em>.registerBuildPlugin([options])
</a>
```

docs(packagejs): fix registerBuildPlugin link

---

_config.yml
source/packages/dynamic-import.md

We likely want to expand on this more, and I haven't decided how much of this should be in the Guide versus here but thought I'd drop this here for starters as we've certainly exhausted our runway of using blog posts and PRs as the docs for this awesome feature!  Maybe the guide could link here to get starter information on how to use it and then go into advanced techniques, like dynamically importing Meteor packages (and how to make Meteor packages work with dynamic imports)?  Input appreciated!
/cc @hwillson

Initial pass at `dynamic-import` package details.

---

source/packages/bundle-visualizer.md

One other thing that might be worth adding is to let people know to remove the `force-ssl` package. Otherwise the app keeps redirecting to https, which localhost doesn't seem to allow?

Add note about 1.5.1's --extra-packages flag

---

source/packages/modules.md

Added info on the option `{ lazy: true }` for api.mainModule to Module docs.
I'd also like to propose adding the `api.mainModule` syntax to the [`Package.js`](http://docs.meteor.com/api/packagejs.html) docs, since that's where I think most people look for the Package.js api.
I'd also like to add info on using `{ isImport: true }` for sass/less/stylus to the api docs somewhere rather than being [buried in the guide](https://guide.meteor.com/writing-atmosphere-packages.html#adding-style)

Add docs for lazy mainModule

---

source/api/mobile-config.md

Update App.icons and App.launchScreens example code to match valid key values listed in detail sections below. The current `iphone` values give an invalid key warning during build.

Update App.icons and App.launchScreens examples

---

jsdoc/jsdoc.sh
source/api/collections.md

Note: jsdoc failed for me on a clean checkout with
```
ERROR: Unable to parse /Users/glasser/Projects/Meteor/docs/code/packages/ejson/ejson.js: 'import' and 'export' may only appear at the top level
```
I note that there wasn't a package-lock.json until I ran `npm install` so maybe we need to lock some transitive deps (as suggested by @abernix)?  I also added a line to jsdoc.sh so that jsdoc failures actually prevent the server from running.

collections: add warnings about allow/deny

---

source/api/connections.md

`DDP.connect` `onReconnect` has been deprecated, so these changes remove the `onReconnect` documentation. The newly supported `DDP.onReconnect` function documentation has been added in. These changes relate to https://github.com/meteor/meteor/pull/9092 and shouldn't be merged in until (unless) that PR is accepted. Thanks!

Remove deprecated DDP.connect onReconnect docs

---

source/packages/server-render.md

As of React 16, using `ReactDOM.render` in the manner demonstrated in the `server-render` docs will cause a React deprecation warning. Switching to `ReactDOM.hydrate` will avoid this. From the React docs:
> Using ReactDOM.render() to hydrate a server-rendered
> container is deprecated and will be removed in React 17.
> Use hydrate() instead.
Source: https://reactjs.org/docs/react-dom.html#render
Thanks!

Replace ReactDOM.render with ReactDOM.hydrate

---

source/api/collections.md

Fixes #157. The changes made in https://github.com/meteor/meteor/pull/8888 probably won't be available until Meteor 1.6, so we should probably hold off on merging this until 1.6 has been launched. Thanks!

Mention that Cursors now support ES2015 iteration protocols.

---

source/commandline.md

This pull request inserts the `--inspect` and `--inspect-brk` notes from `History.md` on the main repo, so that developers are guided away from the `meteor debug` command if they are referencing the API documentation.

Update `meteor debug` documentation for 1.6

---

source/api/mobile-config.md

As discussed in https://github.com/meteor/meteor/issues/4234, re-configuring a plugin which has been previously configured with `App.configurePlugin` may require the `.meteor/local/cordova-build` directory to be manually cleared.
Closes #176.

Mobile: Re-configuring via App.configurePlugin may require manual intervention.

---

package-lock.json
package.json

I'm open to improving this newly created [`chexo`](https://npm.im) npm, but at
the very least, this makes the duplication of the `npm-scripts` across various
`package.json` files (in all the docs repositories) a bit more DRY.

Switch to using `chexo` to simplify the arguments for `hexo` commands.

---

source/packages/server-render.md

I switched `renderToString` to `renderToNodeStream` and noticed that the stylesheet that styled-components generate is empty.
This happens when using `sink.appendToHead(sheet.getStyleTags());` alongside `renderToNodeStream`.
The Solution is to use the new `sheet.interleaveWithNodeStream`. With this approach, the styles are appended to the body instead of the head, but this should have no impact.
See also https://www.styled-components.com/docs/advanced#streaming-rendering
Would be good to have a meteor-section on that page as well ;-) Maybe someone can open a PR there?
In order to prevent others from falling into that pit, i thought it would be worth to have it mentioned in the meteor docs :-)

Document `renderToNodeStream`

---

source/api/pubsub.md

Add a line about the fact that a pub/sub is not rerun when this.userId changes if it threw an error previously.
Fix #172.

Document this.userId edge behavior in publications

---

source/commandline.md

Added the packages that I saw after creating a new project with 
`meteor create testProject --minimal` 
and then running 
`meteor list`
Output:
```
ecmascript             0.11.1* Compiler plugin that supports ES2015+ in all .js files
es5-shim               4.8.0  Shims and polyfills to improve ECMAScript 5 support
meteor                 1.9.2  Core Meteor environment
server-render          0.3.1  Generic support for server-side rendering in Meteor apps
shell-server           0.3.1* Server-side component of the `meteor shell` command.
standard-minifier-css  1.4.1* Standard css minifier used with Meteor apps by default.
standard-minifier-js   2.3.4* Standard javascript minifiers used with Meteor apps by default.
static-html            1.2.2  Define static page content in .html files
webapp …
```

Add minimal flag packages

---

scripts/changelog.js

The Meteor docs use a RegExp to remove the `v.NEXT` section from the documentation, but the new `Breaking changes` and `Migration steps` blocks weren't being removed from the `v.NEXT` section, resulting in a weird look when I first bumped them to 1.8.0.2, as seen in this screenshot from #558's deploy preview:
https://c.jro.cc/722335ff832c
This should fix that!

Fix CHANGELOG generator to accommodate breaking/migration steps in `v.NEXT`.

---

_config.yml
source/api/reactive-dict.md

The text is a little rough, but a start in actually documenting `reactive-dict`.
This commit won't build as it needs the JSDoc comments from meteor/meteor#10273 to build successfully.

Fix #52 - Add reactive-dict to docs

---

source/api/collections.md

Add a paragraph about what is the behavior of a collection when it's only declared client side and it's named. 
Explicits the need to use low-level publication interface in order to populate the named collection and consume data from the client.
Fix #109.

Document client side collection name

---

conversion/old-toc.js
source/packages/browser-policy.html
source/packages/browser-policy.md

Fixes #488
Despite the work done in the guide to [recommend Helmet](https://github.com/meteor/guide/pull/750), it looks like `browser-policy` is still an official package and should really be in docs.
Let me know if you want the content changed or commits squashed

Restore browser policy page

---

source/packages/underscore.md

The _underscore_ package is not included by default since Meteor 1.7 (https://github.com/meteor/meteor/pull/9596), so this removes the mention of _underscore_ being included by default and `_` being in the global namespace.

Remove mention of underscore being included by default

---

source/packages/webapp.md

A ton of sites want an informational continuous landing page that loads instantly backed by a feature rich web application that delivers.
So I really think something like this should be included in the documentation for WebApp - you guys might disagree but given the age old Meteor slow initial page load complaint and where server-render doesn't play nice with Blaze, it's would be good to present this option for folks who want a really performant landing page but depend on the amazing things Meteor brings to the table once the user decides to do something. 
Cheers

Add static landing page implementation details

---

source/commandline.md

Docs out of date. 
NODE_OPTIONS="--debug" results in following error message: "--debug is not allowed in NODE_OPTIONS"
Also, `--debug` is now invalid and `--inspect` should be used instead.

Fix NODE_OPTIONS => SERVER_NODE_OPTIONS; --debug => --inspect

---

source/commandline.md

The optional flags were not documented. This adds the flags, including those (--json, --details), added via https://github.com/meteor/meteor/pull/11165

Commandline meteor list optional flags added.

---

source/api/http.md

Notice for `http` package docs about deprecation.
Better start this early as we start deprecating this across the board.
For more background: https://github.com/meteor/meteor/issues/10913

http package deprecation notice

---

source/environment-variables.md

I added METEOR_PROFILE to environment variables page. This was useful in diagnosing what was causing rebuilds to take over 2 minutes.

Added METEOR_PROFILE to Environment Variables documentation

---

source/api/ejson.md

The existing documentation didn't make it clear that `RegExp` objects could be encoded, though I imagined they could.  I updated the list of supported object types to include all those [defined by `builtinConverters`](https://github.com/meteor/meteor/blob/da7b08d4dd227fd3d297e90ede3b9735d73418f6/packages/ejson/ejson.js#L97).
I didn't give examples to show *how* these types are encoded.  I think the existing example suffices to give a flavor, and users can experiment to see what other things can be produced (including `$escape` in some cases).

Document EJSON support for regular expression and special numbers

---

source/api/packagejs.md

We are using a standard to define options for packages and this standard was not documented yet.

Document: Options for Packages

---

_config.yml
source/packages/fetch.md
source/packages/url.md

Per multiple requests I'm adding the initial documentation for `fetch` and `url` packages (since they are the same concept). It is no way near perfect, but I think this can serve as a nice base for further development.

Add small fetch and url documentation

---

source/environment-variables.md

This is part of https://github.com/meteor/meteor/pull/11408.
This should not be pulled in until Meteor v2.3 releases.

Document DDP_DEFAULT_CONNECTION_URL

---

source/commandline.md

Documentation for the `--platforms` flag from https://github.com/meteor/meteor/pull/11437.

Documentation for "--platforms" flag 

---

jsdoc/docdata-jsdoc-template/publish.js
scripts/api-box.js

Handle `@isprototype` tag.
When this tag is used, it assumes that the documentation in the code is for a prototype and that there is no implementation.
`apibox` will make  `importName` and `filepath` undefined for apis with the `@isprototype true` tag.
This is particularly useful for documenting callback function prototypes.

Handle isprototype tag
