Contributing.md, assets/api-box.html
=> Version NEXT

source/api/methods.md
=> Instruct users to add DDPRateLimiter if they want to use it.

source/packages/accounts-ui.md
Since currently it's showing `{{dstache}}> loginButtons}}`
=> Replace left-over "dstache" residue with mustaches

source/api/assets.md
I believe this was released with meteor 1.3.
=> add Assets.absoluteFilePath

scripts/dl.js
=> Separates option name and option type in dl script

source/packages/spacebars.md
It looks like this is the intended target: http://blazejs.org/guide/spacebars.html
=> Dead link to blazejs.org/spacebars.html

source/api/collections.md
Hi guys, I'm using Meteor for quite a while.
I just want to add some examples of querying with the sort option.
What do you think?
Thanks
=> Add querying with the sort option examples.

source/api/accounts-multi.md
See https://github.com/meteor/meteor/pull/7699
=> Change for Meteor PR #7699

source/api/ejson.md
As proposed here https://github.com/meteor/meteor/issues/4371
=> Provide example usage of EJSON.addType

source/commandline.md
Very useful when getting started.
=> Meteor create --bare and --full

_config.yml, source/environment-variables.md
Moved over from Guide: https://github.com/meteor/guide/pull/599 @abernix
=> Added a list of environment variables

source/api/email.md, source/environment-variables.md
See: https://github.com/meteor/meteor/pull/8805
=> Fix MAIL_URL documentation

source/api/tracker.md
Spelling fix: wether -> whether
=> fix typo in tracker.md

source/api/accounts.md
Refers to https://github.com/meteor/meteor/issues/8381
=> Precision on services-oauth [clientId | appId | consumerKey]

source/environment-variables.md
Clicking BIND_IP now scrolls to correct section
=> Update link anchor

source/environment-variables.md
The environment variable name MONGO_URL was updated to MONGO_OPLOG_URL
=> Correction of MONGO_OPLOG_URL environment variable

source/api/mobile-config.md
After some troubleshooting in my app, I discovered that the example in the docs was not quite right.
=> Correct syntax of accessRule example

source/commandline.md
Adds some differences between the command line arguments for `meteor create` 
Adds the packages installed for the no argument version for meteor create, the `--full` version, and `--bare` version. 
#122
=> Added context to meteor create arguments

source/packages/bundle-visualizer.md
=> fix bundle visual code comment

circle.yml
Left over from the old deployment system, and no longer necessary.
=> Remove unnecessary deployment artifacts.

source/api/collections.md
In 1.7 we are using MongoDB driver 3.0
=> Link to correct version of MongoDB documentation

source/packages/jquery.md
The link given in the section was outdated. This pull request intents to update it with a working link to the active repo.
=> Update jquery section

package-lock.json, package.json
=> Revert "chore(deps): update dependency hexo-renderer-less to v1 (master)"

package-lock.json, package.json
=> Revert "chore(deps): update dependency hexo-renderer-less to v1 (version-1.6)"

package-lock.json, package.json
=> Revert "chore(deps): update dependency hexo-renderer-less to v1 (version-1.5)"

package-lock.json, package.json
=> Revert "chore(deps): update dependency hexo-renderer-less to v1 (version-1.4)"

package-lock.json, package.json
=> Revert "chore(deps): update dependency hexo-renderer-less to v1 (version-1.3)"

source/api/collections.md
I had to read this [article](https://blog.meteor.com/using-promises-and-async-await-in-meteor-8f6f4a04f998) to figure it out, so this could be helpful for other people!
=> Add explanation about promise-like raw collection

package-lock.json, package.json
It's been a while since I updated the docs site, so I might be missing some details. I guess we'll see what the Netlify preview looks like!
=> Update to Meteor 1.8.1

source/packages/server-render.md
Made it clear there are server-only methods that can be used during SSR.
Copied documentation from the main package readme file
=> Included server-only methods

source/api/packagejs.md
Updated the link for CoffeeLint.
=> Broken Link Fixed

source/packages/modules.md
Replace aldeed:simple-schema import line with the NPM version.
=> Replace aldeed:simple-schema with npm

source/packages/dynamic-import.md
Aims to solve #394 
Also took the liberty of including @benjamn's words from [here](https://github.com/meteor/meteor/pull/8327#issuecomment-281428641) and [here](https://github.com/meteor/meteor/pull/8327#issuecomment-280876264) explaining the difference between Meteor's system and other bundling tools.
Happy to take constructive feedback on content, writing style, structure, grammar, etc!
=> Dynamic import expressions

source/packages/appcache.md
This is implemented in PR https://github.com/meteor/meteor/pull/10901
=> Add documentation for `enableCallback` option

source/commandline.md
Related to pull request https://github.com/meteor/meteor-feature-requests/issues/182
=> Added create flag for react

source/api/collections.md
Description in the Code PR https://github.com/meteor/meteor/pull/10976
=> Doc: Adds support to override mongo options via Meteor settings

scripts/api-box.js, source/api/accounts.md
Ref issue https://github.com/meteor/meteor/issues/10469.
Depends on PR https://github.com/meteor/meteor/pull/10818 making it into a release.
Related PR for the Guide: https://github.com/meteor/guide/pull/1022
=> Add explanation of Meteor.user(options) parameter.

source/api/mobile-config.md
Add documentation related to https://github.com/meteor/meteor/pull/9748
=> add App.addResourceFile to mobile config

source/api/accounts-multi.md
As per: https://github.com/meteor/meteor/pull/11049
=> Document beforeExternalLogin hook

source/commandline.md
=> commands meteor publish cover --update flag

source/commandline.md
**Task**: https://trello.com/c/70lUv7nc/541-first-free-deploy-is-considered-a-downgrade
=> #541 - First free deploy is considered a downgrade

source/api/http.md
Small edit to make it easier for people to transition.
=> Add link to fetch package

source/commandline.md
Related: #707 
Sidenote: It's getting very hard to manually maintain the table! Maybe we write a tool, that reads the [skeleton apps](https://github.com/meteor/meteor/tree/devel/tools/static-assets) packages files and creates the table for use?
=> updated meteor create flags and packages table

source/api/packagejs.md
Add a notice about the package deprecation feature and update the code to that feature so that the relevant comments appear int he documentation.
=> Package deprecation feature notice

source/environment-variables.md
Finally getting around to documenting this environment variable.
See https://github.com/meteor/meteor-feature-requests/issues/154#issuecomment-763012319
=> Document METEOR_SQLITE_JOURNAL_MODE

source/commandline.md
=> Document --mobile-settings

source/environment-variables.md
Documented environment variables UNIX_SOCKET_PATH and UNIX_SOCKET_PERMISSIONS
=> Documented environment variables UNIX_SOCKET_PATH and UNIX_SOCKET_PERMISSIONS

source/packages/markdown.md
updated docs of markdown package, about lazy loading of markdown package
actual PR of markdown package https://github.com/meteor/meteor/pull/11443
=> docs: lazy load of markdown package

source/environment-variables.md
Documented environment variable UNIX_SOCKET_GROUP
=> Documented environment variable UNIX_SOCKET_GROUP

source/api/accounts-multi.md
Per https://github.com/meteor/meteor/pull/11472.
I wasn't sure about pushing changes to the `code` git submodule, so I am not sure if this will build until the referenced pull request is merged in. If there are any suggestions for that, I would be happy to make changes.
=> document setAdditionalFindUserOnExternalLogin login hook

_config.yml, source/api/environment.md
Depends on https://github.com/meteor/meteor/pull/11204
=> Document Meteor.EnvironmentVariable

source/commandline.md
Gives concrete examples for both Win and Linux as described [in this issue. ](https://github.com/meteor/meteor/issues/11606)
=> Doc improvement on how to use SERVER_NODE_OPTIONS

README.md
Had to figure this out, adding documentation to help the next person (or myself later!).
=> Document how to test meteor source changes locally
